graph TD
  subgraph Auth[Authentication]
    EntraID[Entra ID]
  end
  subgraph Storage[Storage]
    AzureTable[(Azure Table Storage)]
  end
  
  subgraph FrontendApp[Frontend]
    FrontendNode[Frontend App]
  end

  subgraph APIs[APIs]
    ConfigAPI[Config API]
    PollingAPI[Polling API]
  end
  
  subgraph DownstreamS[Downstream]
    DownstreamServices[Downstream Services]
  end
  
  FrontendNode <-->|Fetch Config / Create Config| ConfigAPI
  FrontendNode -->|Polling Data| PollingAPI
  FrontendNode -->|Authentication| EntraID
  
  ConfigAPI <-->|Store Config / Write Config| AzureTable
  ConfigAPI -->|Authentication| EntraID
  
  
  PollingAPI -->|Send Requests| DownstreamServices
  PollingAPI -->|Fetch Config| AzureTable
  PollingAPI -->|Authentication| EntraID
